### ISSUE TITLE
logo conversion

### ISSUE THREAD

**Issue by fommil** [alexandru/zio-to-scalaz-browser-extension#1]
The ZIO logo should also be changed to the Scalaz logo, otherwise it leads to confusion.

![image](https://user-images.githubusercontent.com/1914041/89899313-fdc2a700-dbd9-11ea-8504-a379bf707eb6.png) (very confusing logo)

![image](https://user-images.githubusercontent.com/1914041/89899328-07e4a580-dbda-11ea-86cc-f4a7514a74ff.png) (not confusing at all)

**Comment by alexandru** [comment]
👍 I'd actually do that, but am too lazy to identify images, PRs welcome 🙂
